syntax = "proto3";

package yandex.cloud.trino.v1;

option go_package = "github.com/yandex-cloud/go-genproto/yandex/cloud/trino/v1;trino";
option java_package = "yandex.cloud.api.trino.v1";

message DataCatalogEventListener {
}

message EventListenersConfig {
  // Configuration of the Data Catalog event listener.
  DataCatalogEventListener data_catalog = 1;
}

message EventListenersConfigSpec {
  // Configuration of the Data Catalog event listener.
  DataCatalogEventListener data_catalog = 1;
}

message UpdateEventListenersSpec {
  // Configuration of the Data Catalog event listener.
  DataCatalogEventListener data_catalog = 1;
}
