syntax = "proto3";

package yandex.cloud.apploadbalancer.v1;

option go_package = "github.com/yandex-cloud/go-genproto/yandex/cloud/apploadbalancer/v1;apploadbalancer";
option java_package = "yandex.cloud.api.apploadbalancer.v1";

// A TLS validation context resource.
message ValidationContext {
  // TLS certificate issued by a trusted certificate authority (CA).
  oneof trusted_ca {
    string trusted_ca_id = 1;

    // X.509 certificate contents in PEM format.
    string trusted_ca_bytes = 2;
  }
}

// Client certificates verification settings.
message ClientCertificatesVerification {
  // If true, ALB will reject connections without a valid client certificate.
  bool require_client_certificate = 1;
  oneof trusted_ca {
    // Trusted certificate authority certificates bundle (PEM text).
    string bytes = 2;
  }

  // If true, ALB will not check certification chain.
  // Backends could use configured client_certificate_forward in Route to proxy certificate and validate it there.
  // Setting accept_untrusted to true forces ALB to allow expired client certificates too.
  bool accept_untrusted = 3;

  // If true, ALB will allow expired client certificates even if accept_untrusted is set to false.
  // Setting accept_untrusted to true forces ALB to allow expired client certificates too.
  bool allow_expired = 4;
}
